#!/bin/bash

echo 'Initializing docker container...'

# terminate on errors
set -e

#Start mysql 
/etc/init.d/mysqld start
    
# A file in a docker volume to be persisted. This file also is used to know if backup must be restored or not.
MYSQL_PASSWORD_FILE="/var/lib/mysql/autogenerated"

if [ ! -f "$MYSQL_PASSWORD_FILE" ] ; 
then 
	#Create mysql user
	mysql -e "CREATE DATABASE ${MYSQL_DATABASE};"
	mysql -e "CREATE USER ${MYSQL_USER}@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
	mysql -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';"
	mysql -e "FLUSH PRIVILEGES;"
    
	#Set root password
	mysqladmin -u root password $MYSQL_ROOT_PASSWORD
	echo "GENERATED ROOT PASSWORD AS '$MYSQL_ROOT_PASSWORD'"            
	echo "GENERATED USER PASSWORD AS '$MYSQL_PASSWORD'" 
	
	#Disable regeneration of users.
	echo 1 > $MYSQL_PASSWORD_FILE
	
else 

	echo 'Old installation already found!'
fi
    
echo 'Entrypoint finished!'

exec "$@"
